steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-m', '30g', '-t', 'gcr.io/scpworkshop/cornell_sc:alpha', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/scpworkshop/cornell_sc:alpha']
options:
 machineType: 'N1_HIGHCPU_32'
timeout: 9600s